# vim:ft=ansible:ts=2:et:
---
- name: Decrypt SES Credentials via KMS inside AWS
  when: ansible_system_vendor == 'Amazon EC2'
  # when AWS Condition does not work for Lints..
  block:
    - name: Decrypt SES Credentials via KMS # noqa jinja[invalid]
      ansible.builtin.shell: |
        aws kms decrypt --region eu-central-1 --ciphertext-blob fileb://<(echo {{ lookup('ansible.builtin.file', '/etc/postfix/ses_credentials.yml') }} | base64 -d) --output text --query Plaintext | base64 -d
      args:
        executable: /bin/bash
      register: _ses_credentials_kms_decrypted
      changed_when: false
      check_mode: false

    - name: Set _sasl fact
      ansible.builtin.set_fact:
        _sasl: "{{ _ses_credentials_kms_decrypted.stdout | from_yaml }}"
      failed_when: _sasl.username is not defined and _sasl.password is not defined

- name: Create postfix configuration file
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
    owner: root
    group: root

- name: Set /etc/mailname
  ansible.builtin.copy:
    content: "{{ ansible_hostname }}.{{ _postfix.domain }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644

- name: Configure Postfix _sasl
  when:
    - _sasl is defined and _sasl | length
    - _postfix.relay is defined and _postfix.relay | length
  tags:
    - molecule-idempotence-notest
  block:
    - name: Create Source File for SASL Password Map
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - "etc/postfix/sasl_passwd"

    - name: Create Postfix SASL Map
      ansible.builtin.command: postmap hash:/etc/postfix/sasl_passwd
      changed_when: false

    - name: Restrict permissions on Postfix SASL Map
      ansible.builtin.file:
        name: "/etc/postfix/sasl_passwd.db"
        mode: 0640
        owner: root
        group: postfix

  always:
    - name: Delete Temp File for SASL Passwords
      ansible.builtin.file:
        name: "/etc/postfix/sasl_passwd"
        state: absent
      tags:
        - molecule-idempotence-notest

- name: Create aliases
  ansible.builtin.template:
    src: etc/aliases.j2
    dest: /etc/aliases
    mode: 0644
    owner: root
    group: root
  notify: Convert aliases

- name: Configure Postfix tagging transport
  when: _postfix.tagging_transport is defined
  block:
    - name: Create header_checks file
      ansible.builtin.template:
        src: etc/postfix/header_checks.j2
        dest: /etc/postfix/header_checks
        mode: 0644
        owner: root
        group: root

    - name: Add taggingsmtp transport to master.cf
      ansible.builtin.lineinfile:
        path: /etc/postfix/master.cf
        regexp: '^taggingsmtp'
        insertafter: '^smtp.*unix.*smtp$'
        line: 'taggingsmtp      unix  -       -       -       -       -       smtp -o smtp_header_checks=regexp:/etc/postfix/header_checks'

- name: Create transport_maps file
  when:
    - _postfix.tagging_transport is defined
    - _postfix.relay is defined and _postfix.relay | length
  ansible.builtin.template:
    src: etc/postfix/transport_maps.j2
    dest: /etc/postfix/transport_maps
    mode: 0644
    owner: root
    group: root
